const deptCodes = {
    "ACCT": "ACCT",
    "ACSCI": "ACSCI",
    "ADVRT": "ADVRT",
    "AERE": "AER E",
    "AFAM": "AF AM",
    "ABE": "A B E",
    "AGEDS": "AGEDS",
    "AGRON": "AGRON",
    "AFAS": "AFAS",
    "AMIN": "AM IN",
    "ASL": "ASL",
    "AECL": "A ECL",
    "ANS": "AN S",
    "ANTHR": "ANTHR",
    "AESHM": "AESHM",
    "AMD": "A M D",
    "ARABC": "ARABC",
    "ARCH": "ARCH",
    "ARTED": "ARTED",
    "ARTH": "ART H",
    "ASTRO": "ASTRO",
    "ATH": "ATH",
    "ATR": "A TR",
    "ZC": "Z C",
    "BBMB": "BBMB",
    "BCB": "BCB",
    "BCBIO": "BCBIO",
    "BPMI": "BPM I",
    "BIOL": "BIOL",
    "BME": "B M E",
    "BMS": "B M S",
    "BUSAD": "BUSAD",
    "CHE": "CH E",
    "CHEM": "CHEM",
    "CHIN": "CHIN",
    "CE": "C E",
    "CLST": "CL ST",
    "CMDIS": "CMDIS",
    "COMST": "COMST",
    "CRP": "C R P",
    "CDEV": "C DEV",
    "CPRE": "CPR E",
    "COMS": "COM S",
    "CONE": "CON E",
    "CJ": "C J",
    "CYBSC": "CYBSC",
    "CYBE": "CYB E",
    "DANCE": "DANCE",
    "DS": "DS",
    "DES": "DES",
    "DSNS": "DSN S",
    "DIET": "DIET",
    "ECP": "E C P",
    "EEB": "EEB",
    "EEOB": "EEOB",
    "ECON": "ECON",
    "EDADM": "EDADM",
    "ELPS": "EL PS",
    "EDUC": "EDUC",
    "EE": "E E",
    "ENGR": "ENGR",
    "EM": "E M",
    "ENGL": "ENGL",
    "ENT": "ENT",
    "ENTSP": "ENTSP",
    "ENVE": "ENV E",
    "ENSCI": "ENSCI",
    "ENVS": "ENV S",
    "EVENT": "EVENT",
    "FCEDS": "FCEDS",
    "FFP": "FFP",
    "FIN": "FIN",
    "FSHN": "FS HN",
    "FOR": "FOR",
    "FRNCH": "FRNCH",
    "GDCB": "GDCB",
    "GEN": "GEN",
    "GENET": "GENET",
    "GEOL": "GEOL",
    "GER": "GER",
    "GERON": "GERON",
    "GLOBE": "GLOBE",
    "GRST": "GR ST",
    "ARTGR": "ARTGR",
    "HS": "H S",
    "HGED": "HG ED",
    "HIST": "HIST",
    "HON": "HON",
    "HORT": "HORT",
    "HSPM": "HSP M",
    "HCI": "HCI",
    "HDFS": "HD FS",
    "HSCI": "H SCI",
    "IMBIO": "IMBIO",
    "INDD": "IND D",
    "IE": "I E",
    "ARTIS": "ARTIS",
    "IGS": "IGS",
    "ARTID": "ARTID",
    "INTST": "INTST",
    "IALL": "IA LL",
    "ITAL": "ITAL",
    "JLMC": "JL MC",
    "KIN": "KIN",
    "LA": "L A",
    "LATIN": "LATIN",
    "LDST": "LD ST",
    "LLS": "L L S",
    "LAS": "LAS",
    "LIB": "LIB",
    "LING": "LING",
    "MIS": "MIS",
    "MGMT": "MGMT",
    "MKT": "MKT",
    "MATE": "MAT E",
    "MSE": "M S E",
    "MATH": "MATH",
    "ME": "M E",
    "MTEOR": "MTEOR",
    "MICRO": "MICRO",
    "MS": "M S",
    "MCDB": "MCDB",
    "MUSIC": "MUSIC",
    "NREM": "NREM",
    "NS": "N S",
    "NEURO": "NEURO",
    "NUCE": "NUC E",
    "NRS": "NRS",
    "NUTRS": "NUTRS",
    "OTS": "OTS",
    "PERF": "PERF",
    "PHIL": "PHIL",
    "PHYS": "PHYS",
    "PLBIO": "PLBIO",
    "PLP": "PL P",
    "POLS": "POL S",
    "PORT": "PORT",
    "PSYCH": "PSYCH",
    "PR": "P R",
    "RELIG": "RELIG",
    "RESEV": "RESEV",
    "RUS": "RUS",
    "STB": "STB",
    "SOC": "SOC",
    "SE": "S E",
    "SPAN": "SPAN",
    "SPED": "SP ED",
    "SPCM": "SP CM",
    "STAT": "STAT",
    "SCM": "SCM",
    "SUSAG": "SUSAG",
    "SUSE": "SUS E",
    "TSM": "TSM",
    "THTRE": "THTRE",
    "TOX": "TOX",
    "TRANS": "TRANS",
    "UST": "U ST",
    "URBD": "URB D",
    "USLS": "US LS",
    "VCS": "V C S",
    "VDPAM": "VDPAM",
    "VMPM": "V MPM",
    "VPTH": "V PTH",
    "WESEP": "WESEP",
    "WISE": "WISE",
    "WGS": "WGS",
    "WFS": "W F S",
    "WLC": "WLC",
    "YTH": "YTH",
}

module.exports = { deptCodes }